### ISSUE TITLE
Figure out the root cause of ECONNRESET errors

### ISSUE THREAD

**Issue by epicmonkey** [pepyatka/pepyatka-server#239]

**Comment by berkus** [comment]
Possibilities:
* redis connection timeout (closes connection on server side) + enable_command_queue: true on client side doesn't immediately detect connection is down
* default client options were not fully sane re: reconnect timeouts - fixed in PR#248
* tcp keepalive faliure?

Interesting analysis re: Azure redis may give some clues https://github.com/mranney/node_redis/issues/628

**Comment by berkus** [comment]
Moving this to later milestone as it's not a very pressing need atm.

**Comment by epicmonkey** [comment]
watchdog ftw. might be in the new life.
